// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Components__Questions__MatchingDrawingController from "./components/questions/matching_drawing_controller"
application.register("components--questions--matching-drawing", Components__Questions__MatchingDrawingController)

import Components__Questions__MultipleChoiceController from "./components/questions/multiple_choice_controller"
application.register("components--questions--multiple-choice", Components__Questions__MultipleChoiceController)

import Components__Questions__OrderingController from "./components/questions/ordering_controller"
application.register("components--questions--ordering", Components__Questions__OrderingController)

import Components__Questions__TrueFalseController from "./components/questions/true_false_controller"
application.register("components--questions--true-false", Components__Questions__TrueFalseController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
